name: Pull and Push Base Docker Images to Google Artifact Registry

run-name: "Pull: ${{ inputs.REGISTRY }}/${{ inputs.IMAGE }}:${{ inputs.SOURCE_TAG }} -> Push: ${{ inputs.ENVIRONMENT }}-GAR:${{ inputs.TARGET_TAG }}"

on:
  workflow_dispatch:
    inputs:
      IMAGE:
        description: "Base image to pull"
        required: true
        type: string
        default: ""
        
      REGISTRY:
        description: "Select the registry to pull the base image from"
        required: true
        type: choice
        options:
          - docker.io
          - quay.io
          - registry.k8s.io

      SOURCE_TAG:
        description: "Tag to pull from Registry (e.g. 5.7, latest)"
        required: true
        default: "latest"

      TARGET_TAG:
        description: "Tag to push into GAR (e.g. 5.7, internal, latest)"
        required: true
        default: "latest"

      ENVIRONMENT:
        description: "Select the target environment for GCP Artifact Registry"
        required: true
        type: choice
        options:
          - dev

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/gcp-base-images.yaml@gcp
    with:
      IMAGE: ${{ github.event.inputs.IMAGE }}
      REGISTRY: ${{ github.event.inputs.REGISTRY }}
      SOURCE_TAG: ${{ github.event.inputs.SOURCE_TAG }}
      TARGET_TAG: ${{ github.event.inputs.TARGET_TAG }}
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
    secrets: inherit
